### ISSUE TITLE
Avoid using namespace libraries

### ISSUE THREAD

**Issue by xiongtx** [CestDiego/nand2tetris.el#2]
First, thanks for creating this package--it makes working with the Nand2Tetris course much easier!

I would suggest, however, that namespace libraries like `names` be avoided. While they may seem convenient, there are some annoying quirks. For example, if I `eval-defun` on a variable like `-assembler`, I am actually putting a new value into `-assembler`, not `nand2tetris-assembler`.

Also, using customizable variables for directories means that changing the base directory `nand2tetris-core-base-dir` does not propagate the change to all relevant values and functions. There's really no need for these variables; the script functions should just use `nand2tetris-core-base-dir` directly.

**Comment by CestDiego** [comment]
I see. Thank you for your nice feedback. As of this moment I can't work on
this right now. But PRs are welcome. I'll make a reminder to work on this
by the middle. Of next month though.

**Comment by CestDiego** [comment]
Fixed in https://github.com/CestDiego/nand2tetris.el/pull/3 @xiongtx thanks for your feedback again.
